@enter foo(20) -> ASTInterpreter2.@enter foo(20)
Because Juno also exports `@enter` and hence it will be better to be unambiguous. I got this error if I don't specify `ASTInterpreter2` e.g. `@enter foo(20)` gives

WARNING: both ASTInterpreter2 and Juno export "@enter"; uses of it in module Main must be qualified
ERROR: LoadError: UndefVarError: @enter not defined